services: 
  swat4-server-docker: 
    image: ghcr.io/mistercalvin/swat4-server-docker:latest 
    container_name: swat4-server-docker
    environment: 
      PUID: 1000 # Optional: Set the UID for the user inside the container; Default: 1000
      PGID: 1000 # Optional: Set the GID for the user inside the container; Default: 1000
      CONTENT_VERSION: SWAT4  # Required: Choose SWAT4 (0), TSS (1), or enter the name of your mod folder (case-sensitive); Default: SWAT4
      SERVER_NAME: "A SWAT 4 Docker Server" # Required: Name of the Server; Default: A SWAT 4 Docker Server
      SERVER_PASSWORD: # Optional: Password for the Server (alphanumeric characters only); Default: unset
      GAME_TYPE: 2 # Required: Choose Barricaded Suspects (1), CO-OP (2), Rapid Deployment (3), Smash and Grab (4), or VIP Escort (5); Default: CO-OP
      LAN_ONLY: False # Optional: If True, the server is hosted only over the LAN (not internet); Default: False
      SERVER_MAPLIST: "SP-FairfaxResidence,SP-Foodwall,SP-Hospital" # Required: Comma-separated list of map names, without extension; Default: SP-FairfaxResidence,SP-Foodwall,SP-Hospital
      MAX_PLAYERS: 10 # Optional: Maximum amount of players for the server; Default: 10
      ADMIN_PASSWORD: # Optional: Admin password for in-game administration (alphanumeric characters only); Default: unset
      NUM_ROUNDS: 15 # Optional: Number of rounds for each match; Default: 15
      ROUND_TIME_LIMIT: 900 # Optional: Time limit (in seconds) for each round (0 - No Time Limit); Default: 900
      DEATH_LIMIT: 50 # Optional:  How many deaths are required to lose a round (0 - No Death Limit); Default: 50
      MP_MISSION_READY_TIME: 90 # Optional: Time (in seconds) for players to ready themselves in between rounds in a MP game; Default: 90
      POST_GAME_TIME_LIMIT: 15 # Optional: Time (in seconds) between the end of the round and server loading the next level; Default: 15
      QUICK_ROUND_RESET: False # Optional: If true, the server will perform a quick reset in between rounds on the same map, if false, the server will do a full SwitchLevel between rounds; Default: False
      ADDITIONAL_ARGS: # Optional: Comma-separated list of additional arguments to modify; Default: unset
    volumes: 
      - /path/to/your/gamefiles/:/container/swat4
      - swat4-wine:/container/.wine
    ports: 
      - 10480-10483:10480-10483/udp
    restart: unless-stopped

volumes:
  swat4-wine:
    name: swat4-wine
